=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/korisnici.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Korisnici">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Korisnik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime" type="xs:string"/>
                <xs:element name="Prezime" type="xs:string"/>
                <xs:element name="Email" type="xs:string"/>
                <xs:element name="Lozinka" type="xs:string"/>
                <xs:element name="Uloga">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="SLUZBENIK"/>
                            <xs:enumeration value="GRADJANIN"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/korisnicii1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Korisnici xmlns="http://www.ftn.uns.ac.rs/korisnici"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/korisnici file:/C:/Users/TehnoCentar/Desktop/XML-projekat/portal%20sluzbenika/sluzbenik/src/main/resources/korisnici.xsd">
    <Korisnik>
        <Ime>Ime0</Ime>
        <Prezime>Prezime0</Prezime>
        <Email>Email0@gmail.com</Email>
        <Lozinka>Lozinka0</Lozinka>
        <Uloga>SLUZBENIK</Uloga>
    </Korisnik>
    <Korisnik>
        <Ime>Ime0</Ime>
        <Prezime>Prezime0</Prezime>
        <Email>Email1gmail.com</Email>
        <Lozinka>Lozinka0</Lozinka>
        <Uloga>SLUZBENIK</Uloga>
    </Korisnik>
</Korisnici>
