=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/obavestenjecir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/obavestenjecir"
    xmlns:oba="http://www.ftn.uns.ac.rs/obavestenjecir">
    <xs:element name="obavestenje">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="naziv_organa" type="xs:string"/>
                <xs:element name="sediste_organa" type="xs:string"/>
                <xs:element name="broj_predmeta" type="xs:int" nillable="true"/>
                <xs:element name="datum" type="xs:date" nillable="true"/>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="adresa_podnosioca_zahteva" type="xs:string"/>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="uvid" type="oba:tipUvid"/>
                <xs:element maxOccurs="2" name="paragraf">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="broj" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="iznos_troskova" type="oba:tipIznosTroskova"/>
                <xs:element name="dostavljeno" type="oba:tipDostavljeno"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType mixed="true" name="tipUvid">
        <xs:sequence>
            <xs:element name="godina" type="xs:gYear" nillable="true"/>
            <xs:element name="opis_trazene_informacije" type="xs:string"/>
            <xs:element name="ime_dana" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Ponedeljak"/>
                        <xs:enumeration value="Utorak"/>
                        <xs:enumeration value="Sreda"/>
                        <xs:enumeration value="ÄŒetvrtak"/>
                        <xs:enumeration value="Petak"/>
                        <xs:enumeration value="Subota"/>
                        <xs:enumeration value="Nedelja"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_sati" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="8"/>
                        <xs:maxInclusive value="21"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pocetak_akcije" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:time">
                        <xs:minInclusive value="08:00:00"/>
                        <xs:maxInclusive value="20:00:00"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="kraj_akcije" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:time">
                        <xs:minInclusive value="09:00:00"/>
                        <xs:maxInclusive value="21:00:00"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="naziv_zgrade" type="xs:string"/>
            <xs:element name="naziv_ulice" type="xs:string"/>
            <xs:element name="broj_ulice" type="xs:int" nillable="true"/>
            <xs:element name="broj_kancelarije" type="xs:int" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="tipIznosTroskova">
        <xs:sequence>
            <xs:element name="kolicina_novca" type="xs:int" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipDostavljeno">
        <xs:sequence>
            <xs:element name="kojem_M._P._dostavlja" type="xs:string"/>
            <xs:element name="arhiva" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/obavestenje1cir1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje xmlns="http://www.ftn.uns.ac.rs/obavestenjecir"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenjecir file:/C:/Users/TehnoCentar/Desktop/XML_i_web_servisi/dokumenti/xml%20i%20seme/obavestenjecir.xsd">
    <naziv_organa>naziv_organa0</naziv_organa>
    <sediste_organa>sediste_organa0</sediste_organa>
    <broj_predmeta>0</broj_predmeta>
    <datum>2006-05-04</datum>
    <ime>ime0</ime>
    <prezime>prezime0</prezime>
    <naziv>naziv0</naziv>
    <adresa_podnosioca_zahteva>adresa_podnosioca_zahteva0</adresa_podnosioca_zahteva>
    <naslov>O B A V E Š T E Nj E  o stavljanju na uvid dokumenta koji sadrži traženu informaciju i o izradi kopije</naslov>
    <uvid>
        <godina>2006</godina>
        <opis_trazene_informacije>opis_trazene_informacije0</opis_trazene_informacije>
        <ime_dana>Ponedeljak</ime_dana>
        <broj_sati>14</broj_sati>
        <pocetak_akcije>01:01:01.001</pocetak_akcije>
        <kraj_akcije>01:01:01.001</kraj_akcije>
        <naziv_zgrade>naziv_zgrade0</naziv_zgrade>
        <naziv_ulice>naziv_ulice0</naziv_ulice>
        <broj_ulice>0</broj_ulice>
        <broj_kancelarije>0</broj_kancelarije>
    </uvid>
    <paragraf broj="broj1">paragraf0</paragraf>
    <paragraf broj="broj3">paragraf1</paragraf>
    <iznos_troskova>
        <kolicina_novca>0</kolicina_novca>
    </iznos_troskova>
    <dostavljeno>Arhivi</dostavljeno>
</obavestenje>
