=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/zahtevcir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/djordjeognjenovic97/XML-projekat/zahtev"
    xmlns:ftn="https://github.com/djordjeognjenovic97/XML-projekat/zahtev">
    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element fixed="Z A H T E V za pristup informaciji od javnog značaja"
                    name="naziv" type="xs:string"/>
                <xs:element name="organ" type="ftn:TOrgan"/>
                <xs:element name="sadrzaj">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipovi_zahteva">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" name="obavestenje_posedovanje"
                                            type="xs:string"/>
                                        <xs:element minOccurs="0" name="uvid_dokument"
                                            type="xs:string"/>
                                        <xs:element minOccurs="0" name="kopija_dokument"
                                            type="xs:string"/>
                                        <xs:element name="dostavljanje_kopije">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:element minOccurs="0" name="posta"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="elektronska_posta"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="faks"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="drugi_nacin">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="100"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="opis_informacije" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="trazilac_informacije" type="ftn:TTrazilac_informacije"/>
            </xs:sequence>
            <xs:attribute name="mesto" type="xs:string" use="required"/>
            <xs:attribute name="datum" type="xs:date" use="required"/>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="stanje" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="podnet"/>
                        <xs:enumeration value="usvojen"/>
                        <xs:enumeration value="odbijen"/>
                        <xs:enumeration value="odbacen"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="ulica" type="xs:string"/>
                <xs:element name="br_ulice">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TTrazilac_informacije">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element ref="ftn:adresa"/>
            <xs:element name="drugi_kontakt_podaci" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="email" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="TOrgan">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="sediste" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== djordjeognjenovic97/XML-projekat/portal sluzbenika/sluzbenik/src/main/resources/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns="https://github.com/djordjeognjenovic97/XML-projekat/zahtevcir"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/djordjeognjenovic97/XML-projekat/zahtevcir file:/C:/Users/TehnoCentar/Desktop/XML-projekat/portal%20sluzbenika/sluzbenik/src/main/resources/zahtevcir.xsd" mesto="mesto1" datum="2006-05-04" id="id1" stanje="podnet">
    <naziv>naziv0</naziv>
    <organ>
        <naziv>naziv1</naziv>
        <sediste>sediste0</sediste>
    </organ>
    <sadrzaj>
        <tipovi_zahteva>
            <obavestenje_posedovanje>da</obavestenje_posedovanje>
            <uvid_dokument>da</uvid_dokument>
            <kopija_dokument>da</kopija_dokument>
            <dostavljanje_kopije>
                <posta>da</posta>
            </dostavljanje_kopije>
        </tipovi_zahteva>
        <opis_informacije>opis_informacije0</opis_informacije>
    </sadrzaj>
    <trazilac_informacije email="email1">
        <pravno_lice>
            <naziv>naziv2</naziv>
        </pravno_lice>
        <adresa>
            <mesto>mesto0</mesto>
            <ulica>ulica0</ulica>
            <br_ulice>50</br_ulice>
        </adresa>
        <drugi_kontakt_podaci>drugi_kontakt_podaci0</drugi_kontakt_podaci>
    </trazilac_informacije>
</zahtev>

=== djordjeognjenovic97/XML-projekat/dokumenti/zahtevcir.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns="https://github.com/djordjeognjenovic97/XML-projekat"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/djordjeognjenovic97/XML-projekat file:/C:/Users/TehnoCentar/Desktop/zahtevcir.xsd" mesto="mesto1" datum="2006-05-04" id="id1" stanje="podnet">
    <naziv>Z A H T E V za pristup informaciji od javnog znaƒçaja</naziv>
    <organ>
        <naziv>naziv0</naziv>
        <sediste>sediste0</sediste>
    </organ>
    <sadrzaj>
        <tipovi_zahteva>
            <dostavljanje_kopije>
            </dostavljanje_kopije>
        </tipovi_zahteva>
        <opis_informacije>opis_informacije0</opis_informacije>
    </sadrzaj>
    <trazilac_informacije>
        <ime>ime0</ime>
        <prezime>prezime0</prezime>
        <adresa>
            <mesto>mesto0</mesto>
            <ulica>ulica0</ulica>
            <br_ulice>50</br_ulice>
        </adresa>
        <drugi_kontakt_podaci>drugi_kontakt_podaci0</drugi_kontakt_podaci>
    </trazilac_informacije>
</zahtev>
