=== djordjeognjenovic97/XML-projekat/portal poverenika/poverenik/src/main/resources/zalbanaodlukucir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/djordjeognjenovic97/XML-projekat/zalbanaodlukucir"
    xmlns:zo="https://github.com/djordjeognjenovic97/XML-projekat/zalbanaodlukucir"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">

    <xs:element name="zalbaodluka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnosilac_zalbe" type="zo:TPodnosilac_Zalbe"/>
                <xs:element name="naziv_organa" type="xs:string"/>
                <xs:element name="datum_predmeta" type="xs:date"/>
                <xs:element name="broj_predmeta">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sadrzaj" type="zo:tipSadrzaj"/>
                <xs:element name="drugi_podaci_za_kontakt" type="xs:string"/>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mesto">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="stanje" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="kreirano"/>
                        <xs:enumeration value="izjasnjavanje"/>
                        <xs:enumeration value="izjasnjeno"/>
                        <xs:enumeration value="reseno"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="adresa">
        <xs:sequence>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="br_ulice">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipSadrzaj">
        <xs:sequence>
            <xs:element name="datum_zahteva" type="xs:date"/>
            <xs:element name="razlog_zalbe" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPodnosilac_Zalbe">
        <xs:sequence>
            <xs:element name="ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="adresa" type="zo:adresa"/>
        </xs:sequence>
        <xs:attribute name="email" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== djordjeognjenovic97/XML-projekat/portal poverenika/poverenik/src/main/resources/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zo:zalbaodluka xmlns:zo="https://github.com/djordjeognjenovic97/XML-projekat/zalbanaodlukucir"
 xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/djordjeognjenovic97/XML-projekat/zalbanaodlukucir file:/C:/Users/Win10/Documents/GitHub/XML-projekat/portal%20poverenika/poverenik/src/main/resources/zalbanaodlukucir.xsd" stanje="kreirano">
    <zo:podnosilac_zalbe email="email0">
        <zo:ime property="property0">ime0</zo:ime>
        <zo:prezime property="property1">prezime0</zo:prezime>
        <zo:adresa>
            <zo:mesto>mesto0</zo:mesto>
            <zo:ulica>ulica0</zo:ulica>
            <zo:br_ulice>50</zo:br_ulice>
        </zo:adresa>
    </zo:podnosilac_zalbe>
    <zo:naziv_organa>naziv_organa0</zo:naziv_organa>
    <zo:datum_predmeta>2006-05-04</zo:datum_predmeta>
    <zo:broj_predmeta property="property2">broj_predmeta0</zo:broj_predmeta>
    <zo:sadrzaj>
        <zo:datum_zahteva>2006-05-04</zo:datum_zahteva>
        <zo:razlog_zalbe>razlog_zalbe0</zo:razlog_zalbe>
    </zo:sadrzaj>
    <zo:drugi_podaci_za_kontakt>drugi_podaci_za_kontakt0</zo:drugi_podaci_za_kontakt>
    <zo:datum property="property3">2006-05-04</zo:datum>
    <zo:mesto property="property4">mesto1</zo:mesto>
</zo:zalbaodluka>
